# version format
version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

skip_commits:
  files:
  - docs/*
  - README.md

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- nuget restore

after_build:
- nuget pack RegenerativeDistributedCache -Prop Configuration=Release -Prop Platform=AnyCPU
- nuget pack RegenerativeDistributedCache.Redis -Prop Configuration=Release -Prop Platform=AnyCPU

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level - quiet|minimal|normal|detailed
  verbosity: normal

# only master branch deploys to NuGet.org
for:
-
  branches:
    only:
      - master

    configuration: Release
    deploy:
      provider: NuGet
      api_key:
        secure: Z6p8drICTxdQrd2FcCJfX0D0NdWdPLklJ8ELOhrHprK+b7qXsPYvOupSdI+vzoyd
      skip_symbols: false
      artifact: /.*\.nupkg/